import json

data = {'parallel_task_ids': ['1002', '1004'],
        'task_config': {'timeout': 120, 'task_strategy': 'RAISE', 'retry_time': 3, 'notice_type': 'FAILURE',
                        'callback_func': 'send_msg', 'callback_module': 'Email'},
        'task_nodes': [
            {'task_config': None, 'update_time': None, 'task_type': 'start', 'module_version': '1.0.0.1',
             'prev_id': None,
             'task_module': 'BuiltIn', 'task_instance': [], 'method_name': 'start', 'task_id': '1000', 'id': 260,
             'process_id': '1005', 'updater': None, 'creator': None, 'desc': None, 'task_name': 'start',
             'next_id': '1001',
             'method_kwargs': {}, 'insert_time': '2023-08-10 21:35:27'},
            {'task_config': None, 'update_time': None, 'task_type': 'parallel', 'module_version': '1.0.0.1',
             'prev_id': '1001', 'task_module': 'Parallel', 'task_instance': [], 'method_name': 'parallel_task',
             'task_id': '1001', 'id': 261, 'process_id': '1005', 'updater': None, 'creator': None, 'desc': None,
             'task_name': '并行网关', 'next_id': '1006', 'method_kwargs': {}, 'insert_time': '2023-08-10 21:35:27'},
            {'task_config': None, 'update_time': None, 'task_type': 'group', 'module_version': '1.0.0.1',
             'prev_id': '1001',
             'task_module': 'Group', 'task_instance': [], 'method_name': 'task_group', 'task_id': '1002', 'id': 262,
             'process_id': '1005', 'updater': None, 'creator': None, 'desc': None, 'task_name': '任务组1',
             'next_id': '1006',
             'method_kwargs': {'group_ids': ['1003']}, 'insert_time': '2023-08-10 21:35:28'},
            {'task_config': None, 'update_time': None, 'task_type': 'common', 'module_version': '1.0.0.1',
             'prev_id': None,
             'task_module': 'Test', 'task_instance': [], 'method_name': 'test_subtraction', 'task_id': '1003',
             'id': 263,
             'process_id': '1005', 'updater': None, 'creator': None, 'desc': None, 'task_name': '减法', 'next_id': None,
             'method_kwargs': {'a': 10, 'b': 12}, 'insert_time': '2023-08-10 21:35:28'},
            {'task_config': None, 'update_time': None, 'task_type': 'group', 'module_version': '1.0.0.1',
             'prev_id': '1001',
             'task_module': 'Group', 'task_instance': [], 'method_name': 'task_group', 'task_id': '1004', 'id': 264,
             'process_id': '1005', 'updater': None, 'creator': None, 'desc': None, 'task_name': '任务组2',
             'next_id': '1006',
             'method_kwargs': {'group_ids': ['1005']}, 'insert_time': '2023-08-10 21:35:28'},
            {'task_config': None, 'update_time': None, 'task_type': 'common', 'module_version': '1.0.0.1',
             'prev_id': None,
             'task_module': 'Test', 'task_instance': [], 'method_name': 'test_subtraction', 'task_id': '1005',
             'id': 265,
             'process_id': '1005', 'updater': None, 'creator': None, 'desc': None, 'task_name': '减法', 'next_id': None,
             'method_kwargs': {'a': 10, 'b': 12}, 'insert_time': '2023-08-10 21:35:28'},
            {'task_config': None, 'update_time': None, 'task_type': 'end', 'module_version': '1.0.0.1',
             'prev_id': '1001',
             'task_module': 'BuiltIn', 'task_instance': [], 'method_name': 'end', 'task_id': '1006', 'id': 266,
             'process_id': '1005', 'updater': None, 'creator': None, 'desc': None, 'task_name': 'end', 'next_id': None,
             'method_kwargs': {}, 'insert_time': '2023-08-10 21:35:28'}],
        'process_info': {'process_params': None, 'process_name': 'test_parallel_with_group', 'process_id': '1005',
                         'updater': None, 'creator': 'blue', 'desc': None, 'process_config': None,
                         'process_instance_id': 'c4bc5b67378211ee9198001a7dda7111'}
        }

print(json.dumps(data))
