name: orderlines

services:

  orderlines_web:
    container_name: orderlines_web
    image: orderlines:${ORDERLINES_TAG}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "15900:15900"
    env_file:
      - .env
    command: [ "/usr/local/bin/orderlines","runserver" ]

  orderlines_worker:
    container_name: orderlines_worker
    image: orderlines:${ORDERLINES_TAG}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: [ "/usr/local/bin/celery", "runserver" ]

  orderlines_grpc:
    container_name: orderlines_grpc
    image: orderlines:${ORDERLINES_TAG}
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: [ "/usr/local/bin/orderlines", "run_grpc" ]

  mysql:
    container_name: mysql
    healthcheck:
      test:
        [
            "CMD",
            "mysqladmin",
            "-u",
            "${MYSQL_ROOT_USER}",
            "-p${MYSQL_ROOT_PASSWORD}",
            "ping",
            "-h",
            "localhost"
        ]
      interval: 3s
      timeout: 1s
      retries: 5
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ${PROJECT_FILE_PATH}/mysql:/var/lib/mysql
    env_file:
      - .env

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 1s
      retries: 5
