# 配置文件

orderlines:
  # 标准库文件位置
  standard_library_location:
    - "orderlines.libraries"
  # 任务运行失败的回调模块
  callback_module: Email
  # 任务运行失败的回调函数
  callback_func: "send_msg"
  # 重试次数
  retry_time: 3
  # 重试策略的休眠时间
  sleep_time: 1
  # 默认每个任务的运行超时时间为120秒
  task_timeout: 120
  # 默认流程的超时时间
  process_timeout: 120
  version: "1.0.0.1"
  notice_type: "FAILURE"
  task_strategy: "RAISE"

flask:
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  SQLALCHEMY_COMMIT_TEARDOWN: True
  SECRET_KEY: "1dfd00abcsdafgdargdsf"

email:
  # 是否发送邮件
  is_send: False
  # 邮件配置--
  mail_host: "smtp.163.com"
  mail_user: "***"
  mail_pwd: "***"
  # 邮件发送方
  sender: "***@163.com"
  # 邮件接受方
  receivers:
    - "***@qq.com"

celery:
  enable_utc: False
  timezone: "Asia/Shanghai"

logger:
  logger_path: "/orderlines_logs"
  FMT: "%(asctime)s %(levelname)s %(message)s"
  DATE_FMT: "%Y-%m-%d %H:%M:%S"

language:
  language_type: "ZH"

redis:
  host: "127.0.0.1"
  port: 6379
  db: 3

mongodb:
  host: "127.0.0.1"
  port: 27017
  db: "orderlines"
  username: "orderlines"
  password: "orderlines"
  collection: "variable"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  db: "orderlines"
