# !/usr/bin/env python
from conf.config import FlaskConfig

SQLALCHEMY_TRACK_MODIFICATIONS = FlaskConfig.SQLALCHEMY_TRACK_MODIFICATIONS
SQLALCHEMY_COMMIT_TEARDOWN = FlaskConfig.SQLALCHEMY_COMMIT_TEARDOWN
SQLALCHEMY_DATABASE_URI = FlaskConfig.SQLALCHEMY_DATABASE_URI
SECRET_KEY = FlaskConfig.SECRET_KEY.encode("utf-8")
